# Setup
title:        tbox
tagline:      A glib-like cross-platform C library
tagline-cn:   一个用c语言实现的跨平台开发库
keywords:     network,asio,coroutine,xml,json,plist,container,iterator,algorithm,stream,cross-platform,embed,ios,android,linux,c
keywords-cn:  网络开发,开发库,异步io,协程,xml,json,plist,容器,迭代器,算法,流,跨平台,linux,c语言,嵌入式,ios,android
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       waruqi
  url:        http://www.tboox.org 

#Others
markdown: kramdown

# multiple-languages
gems:               ['jekyll-paginate', 'jekyll-multiple-languages']
languages:          ['en', 'cn']
language_default:   'en'
